In [4]:
import numpy as np
import pandas as pd
import scipy
from scipy.spatial import distance
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from scipy.special import rel_entr

In [90]:
Predicted = pd.read_csv("./Stereoscope/Outputs/output_Sim23.csv")
Target=pd.read_csv("./Data/Sim23/target.csv")

In [91]:
Predicted

Unnamed: 0  Alveolar_Type_1  Alveolar_Type_2       B_cells         Basal  \
0             0     9.480972e-08     7.844643e-08  5.052942e-07  1.568669e-07   
1             1     9.101055e-07     4.763290e-01  1.548315e-03  1.426841e-05   
2             2     2.787361e-07     1.104274e-01  7.283437e-03  1.689313e-07   
3             3     1.721290e-07     1.390894e-07  1.823528e-01  1.469625e-05   
4             4     5.595173e-02     4.381942e-07  2.179708e-03  5.571166e-01   
..          ...              ...              ...           ...           ...   
995         995     2.370038e-07     2.736670e-01  1.847704e-07  1.357193e-07   
996         996     4.322930e-07     9.716429e-07  5.725944e-07  2.640365e-07   
997         997     1.832475e-07     2.057315e-07  2.418626e-07  4.375857e-07   
998         998     6.698844e-07     2.221277e-01  9.030054e-03  2.825144e-07   
999         999     1.400045e-06     5.384297e-07  1.755904e-06  9.922329e-07   

            CD4_T         CD8_T      Ciliated     Club cell            DC  \
0    4.261949e-07  1.156602e-07  8.050601e-08  1.019372e-07  1.425411e-05   
1    6.847826e-07  2.502311e-07  7.146333e-04  9.523342e-03  7.159377e-07   
2    9.717518e-07  5.485375e-03  8.989195e-08  2.079658e-02  4.728170e-03   
3    2.538881e-02  2.570638e-06  1.598888e-07  8.998977e-03  2.083013e-07   
4    1.359823e-06  1.764962e-07  1.532644e-02  1.499818e-01  1.939355e-07   
..            ...           ...           ...           ...           ...   
995  1.124677e-07  8.034817e-08  5.746903e-08  6.957475e-07  2.370376e-06   
996  1.304733e-06  8.281761e-02  1.639863e-07  4.516264e-07  1.763208e-06   
997  2.295567e-07  1.232904e-07  5.897200e-04  3.441419e-03  2.681129e-06   
998  1.028125e-06  1.487599e-07  1.322934e-07  5.924265e-01  3.322599e-07   
999  2.435460e-05  5.524470e-01  2.836199e-07  2.993661e-07  1.101329e-06   

      Endothelial    Fibroblast    Macrophage          Mast     Monocytes  \
0    6.611524e-02  1.195335e-01  7.290940e-01  6.188873e-08  6.461993e-02   
1    8.471787e-08  8.927155e-08  4.577219e-01  3.681456e-08  4.511716e-02   
2    3.585738e-02  2.012311e-07  5.929319e-01  8.676360e-08  1.860613e-01   
3    6.716794e-01  8.671605e-02  1.377502e-07  1.350180e-07  2.240854e-07   
4    1.509367e-01  6.580975e-03  8.538414e-08  6.192271e-02  1.649196e-07   
..            ...           ...           ...           ...           ...   
995  7.534150e-04  1.508883e-01  5.745339e-01  1.492121e-04  1.158403e-06   
996  3.181417e-07  3.381443e-07  5.793481e-01  1.971511e-07  2.054427e-01   
997  1.415820e-01  2.161756e-07  6.612443e-01  1.619124e-01  7.234847e-06   
998  1.188587e-06  2.260558e-07  1.065090e-01  5.346077e-08  6.971842e-02   
999  1.874773e-01  4.628738e-06  8.059538e-07  1.065782e-06  1.486849e-06   

     Muscle_cells            NK        Plasma  Proliferating_Macrophage  \
0    2.061327e-02  1.363567e-07  6.261843e-08              7.764456e-06   
1    4.744090e-07  2.342484e-03  4.794110e-08              6.685338e-03   
2    1.275415e-07  3.415615e-02  2.267891e-03              1.762486e-06   
3    1.378221e-02  2.970405e-07  1.106262e-02              1.439804e-07   
4    2.147828e-07  1.181672e-07  9.545418e-08              9.026457e-08   
..            ...           ...           ...                       ...   
995  5.778675e-07  8.611371e-08  3.946466e-08              2.255423e-06   
996  2.510908e-07  1.323769e-01  1.886867e-07              3.895092e-06   
997  1.827282e-07  1.138727e-07  7.863557e-08              3.121800e-02   
998  1.820455e-04  9.513950e-08  5.699466e-08              1.746129e-06   
999  7.210251e-07  2.347689e-01  7.291654e-07              1.092235e-06   

     Proliferating_NK_T  
0          1.677274e-07  
1          2.751069e-07  
2          7.902738e-07  
3          2.504512e-07  
4          2.787930e-07  
..                  ...  
995        1.194941e-07  
996        3.454490e-06  
997        1.960896e-07  
998        1.576911e-

In [92]:
Target

Unnamed: 0  Endothelial   DC  B_cells  Macrophage  CD8_T  CD4_T  \
0             0          3.0  0.0      0.0         6.0    0.0    0.0   
1             1          0.0  0.0      0.0         6.0    0.0    0.0   
2             2          1.0  0.0      0.0         2.0    0.0    0.0   
3             3          8.0  0.0      5.0         0.0    0.0    0.0   
4             4          3.0  0.0      0.0         0.0    0.0    0.0   
..          ...          ...  ...      ...         ...    ...    ...   
995         995          0.0  2.0      0.0         2.0    0.0    0.0   
996         996          0.0  0.0      0.0         2.0    0.0    0.0   
997         997          4.0  0.0      0.0         3.0    0.0    0.0   
998         998          0.0  0.0      1.0         2.0    0.0    0.0   
999         999          1.0  0.0      0.0         0.0    7.0    0.0   

     Muscle_cells  Club cell  Alveolar_Type_2  Basal  \
0             0.0        0.0              0.0    0.0   
1             0.0        0.0              8.0    0.0   
2             0.0        0.0              1.0    0.0   
3             0.0        0.0              0.0    0.0   
4             0.0        0.0              0.0    8.0   
..            ...        ...              ...    ...   
995           0.0        0.0              3.0    0.0   
996           0.0        0.0              0.0    0.0   
997           0.0        0.0              0.0    0.0   
998           0.0        2.0              2.0    0.0   
999           0.0        0.0              0.0    0.0   

     Proliferating_Macrophage  Proliferating_NK_T   NK  Monocytes  Mast  \
0                         0.0                 0.0  0.0        0.0   0.0   
1                         0.0                 0.0  1.0        0.0   0.0   
2                         0.0                 0.0  1.0        3.0   0.0   
3                         0.0                 0.0  0.0        0.0   0.0   
4                         0.0                 0.0  0.0        0.0   2.0   
..                        ...                 ...  ...        ...   ...   
995                       0.0                 0.0  0.0        0.0   0.0   
996                       0.0                 0.0  4.0        0.0   0.0   
997                       0.0                 0.0  0.0        0.0   4.0   
998                       0.0                 0.0  0.0        0.0   0.0   
999                       0.0                 0.0  0.0        0.0   0.0   

     Ciliated  Fibroblast  Alveolar_Type_1  Plasma  
0         0.0         3.0              0.0     0.0  
1         0.0         0.0              0.0     0.0  
2         0.0         0.0              0.0     0.0  
3         0.0         1.0              0.0     0.0  
4         0.0         0.0              0.0     0.0  
..        ...         ...              ...     ...  
995       0.0         3.0              0.0     0.0  
996       0.0         0.0              0.0     0.0  
997       0.0         0.0              0.0     0.0  
998       0.0         0.0              0.0     0.0  
999       0.0         0.0              0.0     0.0  

[1000 rows x 20 columns]

In [93]:
Predicted.drop(columns="Unnamed: 0", inplace=True)
#Predicted.drop(columns="cell_ID", inplace=True)


In [94]:
Target.drop(columns="Unnamed: 0", inplace=True)

In [95]:
for i in range(len(Target)):
    Target.loc[i,:]=Target.loc[i,:]/Target.loc[i,:].sum()

In [96]:
for i in range(len(Predicted)):
    Predicted.loc[i,:]=Predicted.loc[i,:]/Predicted.loc[i,:].sum()
 

In [97]:
columns_p=[]
for i in range(Predicted.shape[1]):
    columns_p.append(Predicted.columns[i])
    

In [98]:
columns_t=[]
for i in range(Target.shape[1]):
    columns_t.append(Target.columns[i])
    

In [99]:
columns_p=sorted(columns_p)
columns_t=sorted(columns_t)

In [100]:
Predicted=Predicted[columns_p]
Target=Target[columns_t]

In [101]:
Target=Target.to_numpy()
Predicted=Predicted.to_numpy()

## Pearson Correlation

In [102]:
num_celltypes=Predicted.shape[1]
d = np.zeros(num_celltypes)
for i in range(0,num_celltypes):
    p=Predicted[:,i]
    t=Target[:,i]
    prs=(np.corrcoef(p,t,rowvar=False))
    d[i]=prs[0,1]

In [103]:
np.mean(np.nan_to_num(d))

0.828989815273712

In [104]:
d

array([0.90020227, 0.91933728, 0.77146356, 0.87358091, 0.72543221,
       0.6583919 , 0.93461751, 0.73195546, 0.84100926, 0.82063628,
       0.89966371, 0.84316   , 0.86502508, 0.82061901, 0.89540359,
       0.77501149, 0.93110699, 0.86300976, 0.68118022])

## Jenson Shannon Divergence

In [105]:
jns=distance.jensenshannon(Predicted,Target,axis=1)
jns=jns[~np.isinf(jns).squeeze()]
np.mean(jns)

0.3013781399191868

## F1 Score, Precision, Recall

In [106]:
thresholds={0.001,0.01,0.1,0.2,0.3}

In [107]:
d = pd.DataFrame(0, index=np.arange(len(thresholds)), columns=["Precision","Recall","F1-score"])
d.index=thresholds
for t in thresholds:
    Predicted_logical=(Predicted>t).astype(int)
    Target_logical=(Target>t).astype(int)
    d.loc[t,"Precision"]=precision_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"Recall"]=recall_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"F1-score"]=f1_score(Target_logical,Predicted_logical,average="micro")

In [108]:
d

Precision    Recall  F1-score
0.100   0.901619  0.711198  0.795167
0.200   0.811654  0.615076  0.699822
0.300   0.631076  0.555011  0.590604
0.010   0.672766  0.949848  0.787650
0.001   0.521256  0.968997  0.677865

In [109]:
Predicted

array([[9.48097290e-08, 7.84464375e-08, 5.05294218e-07, ...,
        6.26184360e-08, 7.76445674e-06, 1.67727416e-07],
       [9.10105538e-07, 4.76328969e-01, 1.54831500e-03, ...,
        4.79411039e-08, 6.68533798e-03, 2.75106879e-07],
       [2.78736072e-07, 1.10427427e-01, 7.28343729e-03, ...,
        2.26789053e-03, 1.76248605e-06, 7.90273777e-07],
       ...,
       [1.83247503e-07, 2.05731473e-07, 2.41862583e-07, ...,
        7.86355671e-08, 3.12180024e-02, 1.96089623e-07],
       [6.69884542e-07, 2.22127707e-01, 9.03005592e-03, ...,
        5.69946721e-08, 1.74612957e-06, 1.57691154e-07],
       [1.40004508e-06, 5.38429762e-07, 1.75590410e-06, ...,
        7.29165444e-07, 1.09223457e-06, 2.52654265e-02]])

In [110]:
Target

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.53333333, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28571429, 0.14285714, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])