In [4]:
import numpy as np
import pandas as pd
import scipy
from scipy.spatial import distance
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from scipy.special import rel_entr

In [131]:
Predicted = pd.read_csv("./Stereoscope/Outputs/output_Sim8-5.csv")
Target=pd.read_csv("./Data/Sim17/target.csv")

In [132]:
Predicted

Unnamed: 0  Astro L1 FGFR3 SERPINI2  Astro L1-6 FGFR3 AQP1  \
0             0             1.328847e-07           8.006554e-07   
1             1             1.385687e-07           9.017426e-03   
2             2             2.360881e-07           9.558741e-04   
3             3             1.036411e-06           1.354284e-04   
4             4             1.855800e-07           2.033854e-07   
..          ...                      ...                    ...   
995         995             1.513325e-07           6.943896e-08   
996         996             7.359738e-08           1.002615e-07   
997         997             3.803196e-08           1.348128e-07   
998         998             2.060213e-03           3.143734e-07   
999         999             2.211050e-07           5.577469e-03   

     Astro L1-6 FGFR3 PLCG1  Endo L2-5 NOSTRIN SRGN  Exc L2 LAMP5 KCNG3  \
0              9.403995e-04            1.129233e-03        1.131335e-06   
1              5.055289e-03            4.075868e-08        3.351200e-03   
2              2.954634e-04            2.750338e-07        4.490486e-07   
3              1.171503e-03            1.311314e-03        4.596255e-02   
4              1.748456e-06            2.690113e-03        8.904635e-03   
..                      ...                     ...                 ...   
995            2.567566e-07            1.380054e-07        6.103723e-06   
996            1.530203e-07            7.147028e-08        5.679056e-07   
997            5.204940e-08            1.001308e-07        8.101367e-06   
998            2.317806e-07            1.514146e-03        2.385197e-02   
999            1.213416e-07            2.034324e-03        1.151661e-01   

     Exc L2 LINC00507 ATP7B  Exc L2 LINC00507 GLRA3  Exc L2-3 LINC00507 DSG3  \
0              1.220397e-06            8.163691e-02             7.566283e-05   
1              6.516920e-07            2.078095e-06             4.974653e-06   
2              2.580959e-06            7.503082e-07             5.037340e-06   
3              2.943474e-06            2.074330e-06             8.342610e-07   
4              2.201320e-02            2.390587e-02             1.013512e-01   
..                      ...                     ...                      ...   
995            1.253177e-02            8.972343e-02             2.365556e-06   
996            7.742007e-07            1.800073e-06             2.172235e-06   
997            4.981780e-06            8.726483e-07             6.388859e-07   
998            7.536323e-03            4.085468e-06             1.812796e-06   
999            1.181142e-01            1.311762e-01             5.649581e-02   

     Exc L2-3 RORB CCDC68  ...  Inh L5-6 VIP COL4A3  Inh L6 SST TH  \
0            1.256885e-01  ...         2.405084e-07   1.514370e-07   
1            9.766171e-07  ...         3.560389e-07   7.365737e-07   
2            6.709266e-07  ...         7.199125e-08   7.579138e-08   
3            1.052768e-06  ...         1.511545e-07   1.292723e-06   
4            1.311871e-06  ...         2.382678e-07   3.687550e-07   
..                    ...  ...                  ...            ...   
995          4.956663e-02  ...         5.693828e-07   3.235091e-07   
996          7.083099e-07  ...         1.350263e-02   2.109379e-07   
997          3.760197e-07  ...         5.111144e-03   6.476166e-07   
998          9.563981e-07  ...         2.429979e-07   1.139350e-06   
999          1.003113e-01  ...         2.188172e-07   7.532256e-08   

     Micro L1-6 TYROBP CD74  OPC L1-6 PDGFRA COL20A1  \
0              6.191567e-03             4.390963e-08   
1              7.147398e-04             5.919675e-07   
2              6.466887e-03             4.289773e-04   
3              1.382926e-03             2.049844e-03   
4              3.067207e-03             8.893093e-08   
..                      ...                      ...   
995            3.520144e-03             1.307730e-07   
996            2.645043e-03             5.103873e

In [133]:
Target

Unnamed: 0  Inh L1-2 SST CCNJL  Exc L5-6 FEZF2 IFNG-AS1  \
0             0                 0.0                      0.0   
1             1                 0.0                      0.0   
2             2                 0.0                      3.0   
3             3                 0.0                      0.0   
4             4                 0.0                      0.0   
..          ...                 ...                      ...   
995         995                 0.0                      0.0   
996         996                 0.0                      0.0   
997         997                 0.0                      0.0   
998         998                 0.0                      0.0   
999         999                 0.0                      0.0   

     Exc L3-5 RORB LINC01202  Exc L2 LINC00507 GLRA3  \
0                        0.0                     0.0   
1                        0.0                     0.0   
2                        0.0                     0.0   
3                        0.0                     0.0   
4                        0.0                     0.0   
..                       ...                     ...   
995                      0.0                     2.0   
996                      0.0                     0.0   
997                      0.0                     0.0   
998                      0.0                     1.0   
999                      0.0                     9.0   

     Oligo L2-6 OPALIN FTH1P3  Exc L5-6 FEZF2 C9orf135-AS1  \
0                         0.0                          2.0   
1                         0.0                          4.0   
2                         0.0                          0.0   
3                         0.0                          0.0   
4                         0.0                          1.0   
..                        ...                          ...   
995                       0.0                          0.0   
996                       0.0                          0.0   
997                       0.0                          0.0   
998                       0.0                          0.0   
999                       0.0                          0.0   

     Exc L3-5 FEZF2 ASGR2  Exc L3-5 RORB LNX2  Exc L5 THEMIS RGPD6  ...  \
0                     0.0                 0.0                  0.0  ...   
1                     0.0                 0.0                  0.0  ...   
2                     0.0                 0.0                  0.0  ...   
3                     0.0                 0.0                  0.0  ...   
4                     0.0                 0.0                  0.0  ...   
..                    ...                 ...                  ...  ...   
995                   0.0                 0.0                  0.0  ...   
996                   0.0                 0.0                  0.0  ...   
997                   0.0                 0.0                  0.0  ...   
998                   0.0                 0.0                  0.0  ...   
999                   0.0                 0.0                  0.0  ...   

     Inh L1 VIP KLHDC8B  Inh L3-6 PAX6 LINC01497  Inh L2 PAX6 FREM2  \
0                   0.0                      0.0                0.0   
1                   0.0                      0.0                0.0   
2                   0.0                      0.0                0.0   
3                   0.0                      0.0                0.0   
4                   0.0                      0.0                0.0   
..                  ...                      ...                ...   
995                 0.0                      0.0                0.0   
996                 0.0                      0.0                0.0   
997                 0.0                      0.0                0.0   
998                 0.0                      0.0                0.0   
999                 0.0                      0.0                0.0   

     Inh L1 PAX6 MIR101-1  Inh L1 LAMP5 NMBR  VLMC L1-5 PDGFRA C

In [134]:
Predicted.drop(columns="Unnamed: 0", inplace=True)
#Predicted.drop(columns="cell_ID", inplace=True)


In [135]:
Target.drop(columns="Unnamed: 0", inplace=True)

In [136]:
for i in range(len(Target)):
    Target.loc[i,:]=Target.loc[i,:]/Target.loc[i,:].sum()

In [137]:
for i in range(len(Predicted)):
    Predicted.loc[i,:]=Predicted.loc[i,:]/Predicted.loc[i,:].sum()
 

In [138]:
columns_p=[]
for i in range(Predicted.shape[1]):
    columns_p.append(Predicted.columns[i])
    

In [139]:
columns_t=[]
for i in range(Target.shape[1]):
    columns_t.append(Target.columns[i])
    

In [140]:
columns_p=sorted(columns_p)
columns_t=sorted(columns_t)

In [141]:
Predicted=Predicted[columns_p]
Target=Target[columns_t]

In [142]:
Target=Target.to_numpy()
Predicted=Predicted.to_numpy()

## Pearson Correlation

In [143]:
num_celltypes=Predicted.shape[1]
d = np.zeros(num_celltypes)
for i in range(0,num_celltypes):
    p=Predicted[:,i]
    t=Target[:,i]
    prs=(np.corrcoef(p,t,rowvar=False))
    d[i]=prs[0,1]

/opt/homebrew/Caskroom/miniforge/base/envs/ML/lib/python3.10/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/opt/homebrew/Caskroom/miniforge/base/envs/ML/lib/python3.10/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


In [144]:
np.mean(np.nan_to_num(d))

0.5078797680973812

In [145]:
d

array([ 0.4779139 ,  0.81521087,  0.72113111,  0.7350402 ,  0.09364338,
        0.14234862,  0.59347009,  0.38920087,  0.71591527,  0.30632392,
        0.28120645,  0.65490483,  0.65267547,  0.27174955,  0.68121341,
        0.18104312,  0.16680078,  0.24135685,  0.56369126,  0.28234446,
        0.21135342,  0.22658367,  0.64826135,  0.62712295,  0.46743469,
        0.30940662,  0.18192912,  0.34050075,  0.14832822,  0.5163178 ,
        0.17158358,  0.59987179,  0.34377746,  0.19184789,  0.74815146,
        0.26276176,  0.34259046,  0.22751897,  0.59622968,  0.24162976,
        0.47602126,  0.74328207,  0.28353385,  0.24370968,  0.21999681,
        0.21900424,  0.26025406,  0.25144892,  0.79947464,  0.53363403,
        0.76369117,  0.77504263,  0.37964816,  0.85387667,  0.78710367,
        0.65012806,  0.28679811,  0.45835701,  0.25617038,  0.68251939,
        0.314324  ,  0.82679538,  0.51883517,  0.72560178,  0.64833045,
        0.64619091,  0.57837885,  0.66379874,  0.72300862,  0.63

## Jenson Shannon Divergence

In [146]:
jns=distance.jensenshannon(Predicted,Target,axis=1)
jns=jns[~np.isinf(jns).squeeze()]
np.mean(jns)

0.6389314408628968

## F1 Score, Precision, Recall

In [147]:
thresholds={0.001,0.01,0.1,0.2,0.3}

In [148]:
d = pd.DataFrame(0, index=np.arange(len(thresholds)), columns=["Precision","Recall","F1-score"])
d.index=thresholds
for t in thresholds:
    Predicted_logical=(Predicted>t).astype(int)
    Target_logical=(Target>t).astype(int)
    d.loc[t,"Precision"]=precision_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"Recall"]=recall_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"F1-score"]=f1_score(Target_logical,Predicted_logical,average="micro")

/opt/homebrew/Caskroom/miniforge/base/envs/ML/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [149]:
d

Precision    Recall  F1-score
0.100   0.478112  0.327647  0.388831
0.200   0.594595  0.009950  0.019573
0.300   0.000000  0.000000  0.000000
0.010   0.155981  0.773016  0.259583
0.001   0.104053  0.808995  0.184389

In [150]:
Predicted

array([[1.32884729e-07, 8.00655454e-07, 9.40399564e-04, ...,
        6.17759442e-08, 4.84972273e-08, 3.30836052e-07],
       [1.38568706e-07, 9.01742381e-03, 5.05528777e-03, ...,
        6.39344445e-08, 6.69601337e-08, 4.77074884e-07],
       [2.36088285e-07, 9.55874809e-04, 2.95463669e-04, ...,
        2.50884006e-03, 4.31730220e-08, 5.19327315e-07],
       ...,
       [3.80319680e-08, 1.34812893e-07, 5.20494215e-08, ...,
        6.47488455e-08, 1.37057323e-03, 2.86509951e-03],
       [2.06021376e-03, 3.14373455e-07, 2.31780621e-07, ...,
        2.98836252e-07, 1.02110738e-07, 1.48818426e-07],
       [2.21104979e-07, 5.57746740e-03, 1.21341571e-07, ...,
        4.17396465e-03, 5.45894564e-08, 2.07086303e-03]])

In [110]:
Target

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.53333333, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28571429, 0.14285714, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])