In [4]:
import numpy as np
import pandas as pd
import scipy
from scipy.spatial import distance
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from scipy.special import rel_entr

In [21]:
Predicted = pd.read_csv("./Stereoscope/Outputs/output_Sim18.csv")
Target=pd.read_csv("./Data/Sim18/target.csv")

In [22]:
Predicted

Unnamed: 0         Astro           CA1      CA1-ProS     CA2-IG-FC  \
0             0  2.658796e-10  7.360722e-09  4.692722e-09  1.720037e-08   
1             1  2.626572e-10  4.082468e-08  9.637203e-09  3.360680e-03   
2             2  8.531865e-10  1.469469e-08  6.846003e-09  7.360754e-09   
3             3  4.167446e-09  1.430285e-02  3.913793e-09  3.520403e-09   
4             4  3.113272e-10  7.700786e-09  7.217038e-07  9.173240e-09   
..          ...           ...           ...           ...           ...   
995         995  1.669035e-10  3.508225e-09  2.520269e-09  5.336118e-09   
996         996  8.625952e-10  7.346475e-08  1.746680e-02  1.317317e-08   
997         997  4.583205e-10  7.110780e-09  3.918491e-02  7.798361e-09   
998         998  7.115083e-10  1.257855e-07  6.644160e-08  2.098823e-02   
999         999  2.915607e-10  6.875423e-09  8.354305e-09  2.451051e-09   

              CA3            CR        CT SUB          Car3            DG  \
0    1.286883e-08  2.156954e-07  2.237507e-08  5.501953e-03  3.406260e-09   
1    6.513578e-09  2.820749e-03  1.445764e-07  4.445449e-09  1.112851e-08   
2    3.925636e-08  1.296866e-03  1.374166e-08  6.656133e-01  1.164223e-08   
3    1.034539e-08  3.511766e-03  1.003970e-08  1.158897e-08  9.323294e-09   
4    2.296843e-09  6.019253e-09  1.898732e-02  2.867727e-09  3.594866e-09   
..            ...           ...           ...           ...           ...   
995  4.331315e-09  1.580203e-09  3.712209e-02  2.412188e-09  1.826357e-09   
996  2.845335e-08  1.469223e-08  1.749469e-02  4.103144e-09  4.003588e-01   
997  9.271587e-09  1.580119e-03  2.215212e-07  3.213023e-09  6.350021e-09   
998  1.539036e-08  1.062490e-03  2.552039e-08  4.994616e-01  3.438059e-03   
999  2.137309e-09  2.787740e-09  7.764130e-09  1.470874e-09  2.175313e-09   

     ...         Oligo          Pax6         Pvalb      SMC-Peri  \
0    ...  3.820354e-10  1.088588e-09  6.786740e-10  6.765969e-10   
1    ...  2.081796e-10  7.119019e-02  2.323839e-01  4.026829e-10   
2    ...  1.193763e-09  2.667146e-09  1.740712e-09  1.039258e-04   
3    ...  4.201318e-04  5.792624e-02  1.648721e-09  5.655302e-10   
4    ...  3.206197e-10  1.825442e-08  2.564379e-01  9.096006e-10   
..   ...           ...           ...           ...           ...   
995  ...  1.540305e-10  6.832586e-10  4.548061e-10  4.063395e-10   
996  ...  7.473311e-10  3.845558e-08  5.276732e-01  1.361703e-09   
997  ...  2.678945e-10  8.803251e-09  3.203036e-01  5.776060e-10   
998  ...  5.024007e-10  4.034616e-09  1.818119e-09  3.031198e-09   
999  ...  4.099343e-04  1.888610e-09  2.077946e-09  5.625382e-10   

              SUB      SUB-ProS          Sncg           Sst     Sst Chodl  \
0    5.747894e-09  9.006790e-09  7.210673e-10  5.177724e-10  3.448221e-10   
1    9.855783e-09  6.097610e-09  1.256673e-09  1.367899e-09  1.082801e-02   
2    6.181914e-09  7.006534e-09  2.215913e-09  1.598199e-09  9.455104e-10   
3    7.735639e-09  8.025444e-04  2.116682e-09  7.058698e-10  1.196754e-09   
4    2.975322e-02  2.714107e-03  1.047776e-09  9.026968e-10  6.378028e-10   
..            ...           ...           ...           ...           ...   
995  4.208943e-09  3.401898e-09  3.848084e-10  2.973079e-10  1.948644e-10   
996  2.366076e-08  1.963567e-08  6.885072e-08  6.384318e-03  1.178275e-08   
997  3.064613e-08  1.497464e-08  1.173903e-09  3.684109e-09  3.258766e-09   
998  4.857125e-08  8.594383e-09  3.222260e-09  6.609921e-02  3.933339e-03   
999  1.944467e-06  2.830345e-08  7.153000e-10  7.186271e-10  3.366228e-10   

              Vip  
0    4.943796e-10  
1    6.742811e-10  
2    1.498957e-09  
3    6.451048e-10  
4    5.756625e-10  
..            ...  
995  2.867519e-10  
996  2.068287e-02  
997  6.594857e-10  
998  1.136862e-09  
999  4.530596e-10  

[1000 rows x 55 columns]

In [23]:
Target

Unnamed: 0  L5 PT CTX  L5 IT CTX  L5_6 IT CTX  L4_5 IT CTX  L6 IT CTX  \
0             0        0.0        1.0          0.0          2.0        0.0   
1             1        0.0        0.0          0.0          1.0        0.0   
2             2        0.0        0.0          0.0          0.0        0.0   
3             3        0.0        0.0          0.0          3.0        0.0   
4             4        4.0        0.0          0.0          2.0        1.0   
..          ...        ...        ...          ...          ...        ...   
995         995        0.0        0.0          0.0          6.0        0.0   
996         996        0.0        0.0          0.0          0.0        0.0   
997         997        0.0        0.0          0.0          0.0        0.0   
998         998        0.0        0.0          0.0          2.0        0.0   
999         999        3.0        0.0          0.0          0.0        0.0   

     L6 CT CTX  L5 NP CT CTX   Pvalb  Vip  ...  L6 IT ENTl  L2 IT PAR  CT SUB  \
0          4.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   
1          2.0            0.0    2.0  0.0  ...         0.0        0.0     0.0   
2          0.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   
3          0.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   
4          0.0            0.0    2.0  0.0  ...         0.0        0.0     0.0   
..         ...            ...    ...  ...  ...         ...        ...     ...   
995        8.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   
996        1.0            0.0    4.0  1.0  ...         0.0        0.0     0.0   
997        3.0            0.0    4.0  0.0  ...         0.0        0.0     0.0   
998        1.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   
999        0.0            0.0    0.0  0.0  ...         0.0        0.0     0.0   

     NP PPP  L2 IT ENTm  L2_3 IT HATA  L2_3 IT APr  L5 PPP  L2_3 IT PPP  \
0       0.0         0.0           0.0          0.0     0.0          0.0   
1       0.0         0.0           0.0          0.0     0.0          0.0   
2       0.0         0.0           0.0          0.0     0.0          0.0   
3       0.0         0.0           0.0          0.0     0.0          0.0   
4       0.0         0.0           0.0          0.0     0.0          0.0   
..      ...         ...           ...          ...     ...          ...   
995     0.0         0.0           0.0          0.0     0.0          0.0   
996     0.0         0.0           0.0          0.0     0.0          0.0   
997     0.0         0.0           0.0          0.0     0.0          0.0   
998     0.0         0.0           0.0          0.0     0.0          0.0   
999     0.0         0.0           0.0          0.0     0.0          4.0   

     NP SUB  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
995     0.0  
996     0.0  
997     0.0  
998     0.0  
999     0.0  

[1000 rows x 55 columns]

In [24]:
Predicted.drop(columns="Unnamed: 0", inplace=True)
#Predicted.drop(columns="cell_ID", inplace=True)


In [25]:
Target.drop(columns="Unnamed: 0", inplace=True)

In [26]:
for i in range(len(Target)):
    Target.loc[i,:]=Target.loc[i,:]/Target.loc[i,:].sum()

In [27]:
for i in range(len(Predicted)):
    Predicted.loc[i,:]=Predicted.loc[i,:]/Predicted.loc[i,:].sum()
 

In [28]:
columns_p=[]
for i in range(Predicted.shape[1]):
    columns_p.append(Predicted.columns[i])
    

In [29]:
columns_t=[]
for i in range(Target.shape[1]):
    columns_t.append(Target.columns[i])
    

In [30]:
columns_p=sorted(columns_p)
columns_t=sorted(columns_t)

In [31]:
Predicted=Predicted[columns_p]
Target=Target[columns_t]

In [32]:
Target=Target.to_numpy()
Predicted=Predicted.to_numpy()

## Pearson Correlation

In [33]:
num_celltypes=Predicted.shape[1]
d = np.zeros(num_celltypes)
for i in range(0,num_celltypes):
    p=Predicted[:,i]
    t=Target[:,i]
    prs=(np.corrcoef(p,t,rowvar=False))
    d[i]=prs[0,1]

/opt/homebrew/Caskroom/miniforge/base/envs/ML/lib/python3.10/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/opt/homebrew/Caskroom/miniforge/base/envs/ML/lib/python3.10/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


In [34]:
np.mean(np.nan_to_num(d))

0.6853941568521136

In [35]:
d

array([0.95336547, 0.9025138 , 0.60014902, 0.08715356, 0.92110788,
       0.23439091, 0.4799102 , 0.94728565, 0.95938448, 0.87226573,
       0.62343873,        nan, 0.91868148, 0.56806237, 0.87658519,
       0.5531116 , 0.6295432 , 0.82679674, 0.70778233, 0.2709703 ,
       0.79122571, 0.68408283, 0.93180564, 0.718039  , 0.85759815,
       0.7892441 , 0.17863983, 0.4685093 , 0.9040739 , 0.74881235,
       0.9106281 , 0.54970805, 0.88582389, 0.87490103, 0.52448202,
       0.90621675, 0.66574358, 0.84057733, 0.63122045, 0.26609194,
       0.95916224, 0.67699067, 0.55660995, 0.27363352, 0.93859087,
       0.42121842, 0.88588792, 0.91282721, 0.81384118, 0.32351125,
       0.70390425, 0.86565637, 0.74795806, 0.87156997])

## Jenson Shannon Divergence

In [36]:
jns=distance.jensenshannon(Predicted,Target,axis=1)
jns=jns[~np.isinf(jns).squeeze()]
np.mean(jns)

0.37168501999193015

## F1 Score, Precision, Recall

In [164]:
thresholds={0.001,0.01,0.1,0.2,0.3}

In [165]:
d = pd.DataFrame(0, index=np.arange(len(thresholds)), columns=["Precision","Recall","F1-score"])
d.index=thresholds
for t in thresholds:
    Predicted_logical=(Predicted>t).astype(int)
    Target_logical=(Target>t).astype(int)
    d.loc[t,"Precision"]=precision_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"Recall"]=recall_score(Target_logical,Predicted_logical,average="micro")
    d.loc[t,"F1-score"]=f1_score(Target_logical,Predicted_logical,average="micro")

In [166]:
d

Precision    Recall  F1-score
0.100   0.785969  0.793756  0.789843
0.200   0.829254  0.645833  0.726140
0.300   0.748044  0.351729  0.478478
0.010   0.363356  0.940286  0.524160
0.001   0.280657  0.949092  0.433210

In [146]:
Predicted

array([[2.00774117e-06, 1.22371228e-06, 7.52548788e-05, ...,
        1.67312337e-06, 1.49213608e-01, 7.22358929e-06],
       [1.16244321e-01, 2.99656944e-01, 4.48190721e-03, ...,
        2.30264811e-06, 1.50368767e-01, 2.68416492e-05],
       [6.77284582e-06, 9.41926275e-02, 1.36541571e-02, ...,
        1.34426716e-03, 8.62679977e-04, 4.16841569e-05],
       ...,
       [2.53591350e-06, 1.56359554e-06, 1.63977703e-05, ...,
        1.68346123e-06, 1.58877933e-01, 6.30522374e-06],
       [1.76032037e-02, 2.29564366e-01, 2.17299546e-02, ...,
        7.25830786e-07, 1.80442307e-02, 4.00396892e-06],
       [3.82856346e-06, 2.40115404e-06, 1.23022622e-05, ...,
        2.45467704e-06, 6.16977070e-06, 4.40741607e-02]])

In [147]:
Target

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.53333333, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28571429, 0.14285714, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])